// react-todo/src/App.js
import React, { useState } from 'react';
import ToDoItem from './ToDoItem';

function App() {
  const [ current, setCurrent] = useState("")
  const [ todos, setTodos] = useState([])

  const handleAddToDo = (e) => {
    e.preventDefault()
    setTodos([ ...todos, { name: current , completed: false }]);
    setCurrent("");
  }

  const handleChange = (e) => {
    setCurrent(e.target.value)
  }

  return (
    <>
      <form>
        <h1>To Do List</h1>
        <input name="name" value={current} onChange={handleChange} ></input>
        <button onClick={handleAddToDo}>Add To Do</button>
      </form>
      <ul>
      {
        todos.map((item,index) => <ToDoItem key={index} todo={item}/>)
      }
      </ul>
    </>
  );
}

export default App;

// vue/src/App.vue
<template>
  <h1>To Do List</h1>
  <form>
    <input name="name" v-model="current" />
    <button v-on:click="onAddToDo">Add to do</button>
  </form>
  <to-do-item 
    v-for="(todo,index) in todos" 
    v-bind:key="index"
    v-bind:todo="todo"
  />
</template>

<script>
import ToDoItem from './components/ToDoItem.vue'

export default {
  name: 'App',
  data:() => ({
    current: "",
    todos: []
  }),
  methods:{
    onAddToDo: function(e){
      e.preventDefault();
      this.todos.push({ name: this.current , completed: false });
      this.current = ""
    }
  },
  components: {
    ToDoItem
  }
}
</script>
